### ISSUE TITLE
Can't get this working...

### ISSUE THREAD

**Issue by boikedamhuis** [Tharos/garmin-uploader#1]
What do I have to do if I want to get this script working? Your code in your readme looks very simple, and will be very useful for me! How can I get the rest working? :smile:

**Comment by Tharos** [comment]
Hello! Unfortunately Garmin redesigned and changed sign-in implementation on Garmin Connect some time ago and that has broken this small library. You will have to use some different approach. :(

**Comment by boikedamhuis** [comment]
Ah... 😧 But hey, thanks for your fast response! :)

**Comment by Tharos** [comment]
You're welcome. :)
